### PR TITLE
remove DR matrix kb

### PR DESCRIPTION
**Pull request by chrislittle**
remove DR matrix kb as its focus was on premium storage

### CODE REVIEW

**Comment by chrislittle** [comment]
Please create a 303 as well as this is a delete in prep for premium retiring

**Comment by chrislittle** [comment]
unsure why this failed checks as i'm removing an existing kb only.

**Comment by jim-phillips** [comment]
@chrislittle You also have to update Servers/centurylink-cloud-backup-and-recovery-services.md because that references this article.  Do that in this PR to fix the check.

**Comment by chrislittle** [comment]
this is now fixed as well @jim-phillips

**Comment by rpdubose** [comment]
@chrislittle is there a replacement article for this kb? In other words, should we send the any traffic that does find this article to an sbs kb.

**Comment by chrislittle** [comment]
@rpdubose nope there is no replacement as its sole focus was premium storage details.  i'd just redirect to the kb root unless you have some other approach you like to take for completely obsolete kbs

**Pull request merged**
