### PR TITLE
java session persistence to redis

### PR DESCRIPTION
**Pull request by tchughesiv**
maybe it fits here as we discussed?

### CODE REVIEW

**Comment by nathanyoung** [comment]
@csterwa thoughts?

**Comment by csterwa** [comment]
@tchughesiv we are not going to support p-redis coming with the launch. We are working with a 3rd party partner to get this type of session management support. Therefore, I'd like to wait until we do get a 3rd party into marketplace before adding this section.

BTW, this really pains me since you did a great job of showing how to do it. Maybe we can keep this PR open and within a week or 2 be able to modify it for new service.

**Comment by tchughesiv** [comment]
np Chris, i didn't know... what's the 3rd party solution? maybe ping me in
slack?

**Comment by nathanyoung** [comment]
reopen when appropriate.

**Pull request closed without merging**
