### PR TITLE
Master

### PR DESCRIPTION
**Pull request by jmalmadclc**

### CODE REVIEW

**Comment by marycadera** [comment]
@chrislittle - are you able to confirm that the process Jake outlined is in alignment with the "standard way" Christine Parr mentioned in Slack yesterday. Concern was that Operations should ultimately provide this service so that the DBA team can support it consistently.

**Comment by jmalmadclc** [comment]
@marycadera I have asked for specifications in the past and not received any, this is just the process I've used for creating many AlwaysOn AGs. I will happily update it with specifics from Ops or the DBA team if provided.

**Comment by chrislittle** [comment]
can you point out what statement we are worried about?  i don't see anything in this pull request about any Ops or other procedures.  its just how to do a SQL action in the software.

**Comment by marycadera** [comment]
@jmalmadclc, Christine is going to take a look and let us know if there are any updates. Thanks.

**Comment by chrislittle** [comment]
thanks and to be clear this is not a managed KB as far as i know being its going in our general servers area.  Jake, just like myself, writes for non-managed components mostly on how to perform actions like building clusters, configuring services etc for consumption to broad customers that are not managed.  if this was for managed we'd be pushing to the managed part of the KB which generally we don't do unless approved by product

**Pull request merged**
