### PR TITLE
Test pull

### PR DESCRIPTION
**Pull request by jmalmadclc**
Test pull req. with updated article from webui as opposed to client which will not allow pulls. OVF doc has been converted to markdown and is valid aside from date.

### CODE REVIEW

**Comment by nathanyoung** [comment]
@jmalmadclc there are a couple of broken links reported by the commit analyzer. Check the Travis CI build details to view the errors.

**Comment by osbornm** [comment]
The title says "test pull" are we to assume that it wasn't meant to be merged/pulled? If we don't hear anything I'm going to close this out.  cc @jmalmadclc

**Comment by jmalmadclc** [comment]
Matt,

This was a originally a test-pull from the webui as I was having issues with a pull request from my local machine; however, the contents are viable updates that should be merged- I didn’t think that it would grab them as I thought I had already issued a pull request (same #349) from my local install with an accurate title. I think one of the issues was that I renamed a file locally (that had “tier 3” in the filename and it caused some travis errors (which I’ve since corrected in #378).

Apologies, I think I have my local repo issues sorted so if you could merge this that would be great.

Thanks,

Jake

Jacob Malmad
Sr. Cloud Architect
CenturyLink Cloud 
Mobile: 203.844.0516
Email: jake.malmad@centurylink.com<mailto:jake.malmad@centurylinkcloud.com> 
www.centurylinkcloud.com<http://www.centurylinkcloud.com/>

**Comment by osbornm** [comment]
@jmalmadclc our build process has identified errors so I cannot merge it until those have been resovled for more information see the [README](https://github.com/CenturyLinkCloud/PublicKB#how-to-make-contributions) point 9 to be exact.

**Comment by jmalmadclc** [comment]
Close this one and I will re-submit with a real title as I forgot to put a space in my header formatting anyway. The travis error is very strange:

“File '/home/travis/build/CenturyLinkCloud/PublicKB/Service Tasks/&' not found. Is there a file extension? Are the file extension and path correct? (Referenced from '/home/travis/build/CenturyLinkCloud/PublicKB/Service Tasks/best-practices-and-preparation-for-a-virtual-machineovfova-import.md')”



There is not a single ampersand character in the entire article and nor is there a file with that name- any ideas what would cause this? Hoping maybe if this is close and I resubmit that it will go through. The markdown preview in atom looks perfect (now) and I am at a loss.



Jake

Jacob Malmad
Sr. Cloud Architect
CenturyLink Cloud 
Mobile: 203.844.0516
Email: jake.malmad@centurylink.com<mailto:jake.malmad@centurylinkcloud.com> 
www.centurylinkcloud.com<http://www.centurylinkcloud.com/>

**Pull request closed without merging**
