### PR TITLE
Update how-do-i-report-a-support-issue.md

### PR DESCRIPTION
**Pull request by pauldougherty**
Hi. I'm trying to fix the "chat system requirements" link as is it broken on the current page. Clicking the link does not take you anywhere. I changed the indentation of the section by adding another "#". The link at the top is indented 2x and the section appears to be indented only once. I am not sure if this solution will work. Can you please verify? I will post in the slack digital channel on Monday for confirmation. Thank you.

### CODE REVIEW

**Comment by chrislittle** [comment]
That is a header not a link. ### is the proper format for a header.

**Comment by pauldougherty** [comment]
Thanks. The link is at the top of the page. I did add a "#" to the header. The link appears to be indented twice where the header seems to be indented once which is why I added another #. Do you think that will fix the issue?

**Comment by chrislittle** [comment]
I'll check Monday to see the issue

**Comment by pauldougherty** [comment]
No worries. Thank you!

**Comment by chrislittle** [comment]
closing.  as this is a sub category i'll do a pull request to change this to a major heading and link it myself

**Comment by chrislittle** [comment]
https://github.com/CenturyLinkCloud/PublicKB/pull/1503 used instead

**Pull request closed without merging**
