### PR TITLE
[EBE-5106] Add documentation on how to add DCC as a provider on CAM

### PR DESCRIPTION
**Pull request by pascualin**
@srveit Could you please review and merge these changes if everything is fine?
Thanks!

### CODE REVIEW

**Comment by rchakra1** [comment]
@srveit @pascualin please hold off on merging . I need to review this

**Comment by pascualin** [comment]
Please @srveit, hold off for merging until @rchakra1 reviews it.
Thanks!

**Comment by rchakra1** [comment]
@pascualin  here are my suggestions

- where ever you have "DCC" change it to "CenturyLink DCC" including the title
- Instead of the first sentence you can just say "Select CenturyLink DCC from the Provider list and provide the username and password that is used to logon to CenturyLink DCC Portal."
- Instead of "will start syncing it" , please say "will start synchronizing the Provider account"
- Instead of "It will load all the different deployment options available to use wth the Policy Boxes and make them available on Cloud Application Manager's UI." can we say "Once the synchronization is complete, Cloud Application Manager will create default Deployment Policies with the different deployment options available"
- After this statement can you add the screenshot of the Deployment Policies here.
- Instead of "The user is normally linked to a company and this company linked to a set of metadata like BillingSite, Clusters, Domains, etc." can we say "The user account used when creating the Provider, is linked to a Company, Billing Site, Clusters, Domains, etc."
- Can you create a subsection of Deploying Instances from Deployment Policies and put the two sections "Virtual machines get deployed on clusters. If Cloud Application Manager doesn't have enough information to deploy a cluster, then the cluster will not be available as a deployment option for the Policy Boxes. Nonetheless, Cloud Application Manager will display an alert, as you can see on the following screenshot:" and "Once the Box deploys, Cloud Application Manager will show the traces of what is happening with the provider. At the end of the process it will show us a script that will have to be manually executed on the newly created Virtual Machine." along with the screenshots

**Comment by pascualin** [comment]
I've updated with your suggestions @rchakra1, please review again.

**Comment by rchakra1** [comment]
@pascualin can you move the sentence "When the synchronization process finishes, the list of Linux and Windows Services available to deploy on each cluster will be available on the provider's "Configuration" tab." and the picture before "Editing....."

**Comment by pascualin** [comment]
@rchakra1 Updated, please check

**Comment by pascualin** [comment]
Hi, @rchakra1, did you get a chance to review this again?
Thanks!

**Comment by rchakra1** [comment]
@pascualin This looks good.

@srveit . Please go ahead and merge

**Pull request merged**
