### PR TITLE
PatchingaaS

### PR DESCRIPTION
**Pull request by bjswoboda**
Third attempt today! Working with Chris Little, updated document with TOC, formatting, and broke out the different ways to execute the script.

This Patching as a Service Job Aid now describes how to use blueprints, group actions, and APIs to execute script packages. Additionally, it describes how to use APIs to collect data regarding updates/patches.

### CODE REVIEW

**Comment by bjswoboda** [comment]
I made the change.

**Comment by bjswoboda** [comment]
I added the .md

**Comment by nathanyoung** [comment]
@chrislittle feel free to merge if this looks good.

**Comment by chrislittle** [comment]
Ben i'm going to merge this.  I suspect once the code goes live you'll find you don't need bold on your steps as it makes it look like everything is bold (headers, steps etc, bold is for important things not every step IMHO).  so just take a peek once they do a push to production and if it looks out of place just do another update later on.   its minor so I don't consider it blocking as this is important to get out there.

**Comment by bjswoboda** [comment]
Thanks. Do you know when this gets pushed to prod? My assumption is that it would be release driven, but I have never heard that specifically stated.

**Pull request merged**
