### PR TITLE
Create appfog_tips.md

### PR DESCRIPTION
**Pull request by tchughesiv**

### CODE REVIEW

**Comment by csterwa** [comment]
Hello @tchughesiv - This is great to see KB article pull requests. I hope that you're able to continue doing this. For this pull request I have a few comments and wanted to let you know that I would not merge this pull request in its current state.

This AppFog tip is interesting but I'm wondering if it is the case that your application automatically does session replication to Redis given this command. I think there is more context, such as type Java application such as Spring Boot, that is needed in order for this to be generally the case.

Also, we are making KB articles that are specific to a solution rather than general tips. In this case, most of the applications deployed onto NextGen AppFog thus far are PHP and Node.js applications and so this tip would be out of context for most users.

I think if you were to add more specific context around the type of Java application along with more specifics on using the Redis service in your application for session management then it could be closer to something we can merge into the KB articles for AppFog. Also, I think the title of the article could be "Binding Redis to [specific type] Java Application".

Let me know what you think. Thanks.

**Comment by osbornm** [comment]
@csterwa Will be reaching out to you to discuss.

**Comment by tchughesiv** [comment]
No problem, but it truly is automatic for tomcat apps with jsessionid in
the java buildpack ... for reference:
https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-tomcat.md#session-replication
http://blog.pivotal.io/cloud-foundry-pivotal/products/session-replication-on-cloud-foundry-2

It's a pretty sweet feature set.  I'll try to add more details/specifics
unless you come back stating different.

**Comment by tchughesiv** [comment]
Would you like to test for yourself first and then merge under another
title?

**Pull request closed without merging**
