### PR TITLE
DBaaS Getting Started Updates Nov24Release

### PR DESCRIPTION
**Pull request by christineparr11**
Added KB article on Replication and Failover feature in MySQL DBaaS

### CODE REVIEW

**Comment by jim-phillips** [comment]
@christineparr11 did you mean to delete this?  Your comment says you are adding a file.

**Comment by christineparr11** [comment]
@jim-phillips - I am trying to add the file.  I actually thought it should have gone with the previous update I made, but I don't see it published, so I was attempting to push it again.

**Comment by jim-phillips** [comment]
@christineparr11 It might not have been published yet, but it is in a different commit.  This PR will delete it.  I am closing this PR.  We will have a kb sync in staging.ctl.io before noon (CST).  Check that.

**Comment by christineparr11** [comment]
Thanks @jim-phillips .  The other changes from my previous pull request were made which is why I thought there was a problem with this specific file.  I will check out staging.

**Pull request closed without merging**
