### PR TITLE
Adding Removing IPS KB article

### PR DESCRIPTION
**Pull request by SeanRobb**
This adds the Client-Security teams removing IPS article along with some updates to the getting started with ips article.

### CODE REVIEW

**Comment by osbornm** [comment]
It is prefered that screenshots be taken with the "standard" green theme that is default in the CLC portal

**Comment by jwebs1** [comment]
@osbornm I'm not sure what you mean by the "standard" green theme. Could you give me an example? Thanks!

**Comment by SeanRobb** [comment]
@osbornm we are going to have to update our KB's once we add windows to our product.  When we do that i will update the screenshots.

**Comment by osbornm** [comment]
@jwebs1 look at any of the screen shots on https://www.ctl.io/ the videos on the front page hero also display the standard green theme.

**Pull request merged**
