### PR TITLE
something like this fit here?

### PR DESCRIPTION
**Pull request by tchughesiv**
i was told by chris sterling ecosystem area may be a better fit... thoughts?

### CODE REVIEW

**Comment by nathanyoung** [comment]
This doc needs the front matter added to the top of the file. See the description in the readme for what's required:

https://github.com/CenturyLinkCloud/PublicKB#overview

**Comment by nathanyoung** [comment]
@csterwa you good with this here?

**Comment by tchughesiv** [comment]
I've added the necessary metadata

**Comment by csterwa** [comment]
@tchughesiv I do think this is not an AppFog article but where are the articles on how to create a Cloud Foundry deployment on CLC?

**Comment by tchughesiv** [comment]
idk, maybe they don't exist yet since pivotal offering/blueprint isn't
public yet?

**Comment by csterwa** [comment]
@tchughesiv I don't think we should include an article that doesn't have supporting context for how to get Cloud Foundry installed. Is this for Pivotal Cloud Foundry? Or your own BOSH deployed open source Cloud Foundry deployment?

**Comment by tchughesiv** [comment]
The notes were built from a pivotal install, but i dialed them down to
apply to any private CF deployment.

**Comment by csterwa** [comment]
@tchughesiv I think you should coordinate with David Shacochis on the alignment with PCF. Also, we don't have a mechanism today to deploy CF on CLC so I'd be hesitant to put out anything about managing a CF installation until we have a way to do so.

**Comment by tchughesiv** [comment]
k, we can wait and ill coordinate with Dave.

**Comment by nathanyoung** [comment]
reopen the request when it's appropriate.

**Pull request closed without merging**
