### PR TITLE
Jruckle patch 1

### PR DESCRIPTION
**Pull request by jruckle**

### CODE REVIEW

**Comment by nathanyoung** [comment]
Jared, since this is a new document it should use markdown syntax instead of HTML.

**Comment by jruckle** [comment]
I thought that I did use markdown for the most part?  maybe i just mis-titled the header tag description.

**Comment by nathanyoung** [comment]
No, you have HTML syntax in the markdown file. Markdown files understand HTML syntax, but we would prefer that new documents be written in standard markdown syntax.

For example, in markdown lists are formatted like this:

```
* First list item
* Second list item
```

instead of 
```
<ul>
<li>First list item</li>
<li>Second list item</li>
</ul>
```

You also have a few extra HTML tags that aren't properly opened or closed. Writing in markdown syntax should prevent this.

**Comment by nathanyoung** [comment]
beautiful, thank you!

**Comment by jruckle** [comment]
85th time is a charm, as they say

**Pull request merged**
