### PR TITLE
fix links in /Ecosystem Partners

### PR DESCRIPTION
**Pull request by thenickcox**
Hi there. Nick from @WINTR here. Just fixing up some docs that my commit analyzer found to reduce the noise of link issues on build failures before I merge in the analyzer.

### CODE REVIEW

**Comment by nathanyoung** [comment]
shouldn't the image links be relative?

**Comment by mattfordham** [comment]
Ah yes, @thenickcox we can chat quick about this.

**Comment by thenickcox** [comment]
@nathanyoung Sorry about the confusion. The image links are relative. Squashed commits.

**Comment by nathanyoung** [comment]
I reverted this because the links to the public ip address page were broken when I pulled this into the PublicPlatform repo.

**Comment by nathanyoung** [comment]
e.g. it generates this link with your fix `http://localhost:3000/knowledge-base/ecosystem-partners/Network/how-to-add-public-ip-to-virtual-machine/`

**Comment by thenickcox** [comment]
@nathanyoung It's become pretty clear to me that I'm lacking the necessary context to make these changes. I'll circle back with @mattfordham. Sorry about this.

**Pull request merged**
