### PR TITLE
Adding Simple Backup FAQ's

### PR DESCRIPTION
**Pull request by jgerger**
Corrected file name and updated an answer

### CODE REVIEW

**Comment by nathanyoung** [comment]
Why did you break you commit the last change? It was fixed.

**Comment by jgerger** [comment]
Sorry, I had another change Chris Little pointed out that needed to be updated as well. I changed the link case before I noticed you changed the case in the getting started guide file name. I have since changed it back but it looks like I now have conflicts.

**Comment by jim-phillips** [comment]
@jgerger Please fix the conflicts.
https://github.com/CenturyLinkCloud/PublicKB#merging-an-upstream-repository-into-your-fork

**Comment by jgerger** [comment]
All conflicts and linking issues are resolved. Sorry for all the confusion, I'm still a GIT newbie.

**Pull request merged**
