### PR TITLE
Add user management documentation

### PR DESCRIPTION
**Pull request by gsanchezu**
@davisein, @rchakra1, @amwatson1s, please review

### CODE REVIEW

**Comment by gsanchezu** [comment]
@davisein, @rchakra1, @amwatson1s, could you please review? Thanks!

**Comment by jim-phillips** [comment]
Waiting on requested reviews

**Comment by gsanchezu** [comment]
Hey @davisein, @rchakra1, @amwatson1s, could you please review? Thanks!

**Comment by rchakra1** [comment]
looks good

**Pull request merged**
