### PR TITLE
Create restarting_cloud_foundry.md

### PR DESCRIPTION
**Pull request by tchughesiv**

### CODE REVIEW

**Comment by osbornm** [comment]
@csterwa Will be reaching out to you to discuss.

**Comment by csterwa** [comment]
@tchughesiv - AppFog doesn't allow for running your own Cloud Foundry therefore I don't believe this is a valid KB article for AppFog. Were you doing this on IaaS servers?

**Comment by tchughesiv** [comment]
I was and am... for both community stacks and pivotal for CTL IT, which
will become an offering soon.  If you like, we can wait on this until its
an actual offering? I just thought it was a nice addition along the lines
of apache tips or windows AD, mysql, etc.  Software stack tips...  not sure
what category it belongs to though?  General?  PaaS?

**Comment by tchughesiv** [comment]
FYI, i believe i submitted this to the General category, not AppFog.

**Comment by tchughesiv** [comment]
Should I resubmit under another category besides General? Let me know...

**Pull request closed without merging**
