### PR TITLE
Add point 7 to explain the required pemissions for temporal user creation

### PR DESCRIPTION
**Pull request by gsanchezu**
@julianatienza, @GustavoLlorente, 👍 ?

### CODE REVIEW

**Comment by jim-phillips** [comment]
@gsanchezu Please resolve conflicts.

**Comment by gsanchezu** [comment]
Hey @jim-phillips, I already resolved conflicts, please review. Thanks!

**Comment by gsanchezu** [comment]
Hey @julianatienza, could you please review?

**Comment by jim-phillips** [comment]
@gsanchezu there are still conflicts.  Sorry if I didn't get back to this in time, but there are still conflicts.

**Comment by gsanchezu** [comment]
Hey @jim-phillips, conflicts solved!

**Comment by julianatienza** [comment]
@ACK I think it's quite detailed. Thanks @gsanchezu

**Pull request merged**
