### PR TITLE
[Branding] Change the screenshots in Managed service section

### PR DESCRIPTION
**Pull request by aryaroudi**
Hey @gsanchezu Please review these changes

### CODE REVIEW

**Comment by aryaroudi** [comment]
> 1. GettingStarted17.png

Hey, @gsanchezu GettingStarted17.png has a different region I don´t know if it is important or not

**Comment by gsanchezu** [comment]
Hey @aryaroudi, you can remove that file (GettingStarted17.png), and also its reference into the corresponding `.md` file

**Comment by aryaroudi** [comment]
> Hey @aryaroudi, you can remove that file (GettingStarted17.png), and also its reference into the corresponding `.md` file

Sure, agree with that

**Comment by gsanchezu** [comment]
Hey @aryaroudi, never mind, I will take care of the above changes

**Pull request merged**
