### PR TITLE
Add CAM AWS Share Shifting KB

### PR DESCRIPTION
**Pull request by DLM1**
1 new file

### CODE REVIEW

**Comment by jkatzen73** [comment]
Is this being published on CTL.io ? its more of an internal doc and shouldn’t be.

Jeff Katzen
Director, Cloud Practice Lead
(914) 574-2791

**Comment by DLM1** [comment]
@lyzalou See the above comment from Jeff Katzen. Please advise.

**Comment by chrislittle** [comment]
agree with @jkatzen73 ... this is internal sales consumption processes which don't belong in a customer facing page. nothing in here is for customers to perform.  processes for share shift have plenty of other spots to live for sales/sellers to consume

**Comment by lyzalou** [comment]
@dlm1 Can you investigate how to adjust this KB so that it covers the customer perspective? 
What does a customer do, if they want to move an account from another 3rd party to CTL and CAM?
What can the customer expect from CTL in terms of support through the process?
How long might it take to make the shift?
What is "on" the customer and what is "on" CTL?

**Pull request closed without merging**
