### PR TITLE
Minor updates and fixes for Cloud Academy

### PR DESCRIPTION
**Pull request by gsanchezu**
@DiegoSanjuan, 👍?

### CODE REVIEW

**Comment by jim-phillips** [comment]
@gsanchezu File '/home/travis/build/CenturyLinkCloud/PublicKB/Cloud Application Manager/Automating Deployments/managing-multi-tier-applications.md' not found.

**Comment by gsanchezu** [comment]
Yep, sorry, I just updated the links. Thanks @jim-phillips 

Hey @JimGreene30, I've renamed `managing-multi-tier-applications.md` to `managing-multi-tier-applications-with-bindings.md`. Could you please add a redirect in ctl.io as Jim suggested? Thanks!

**Comment by gsanchezu** [comment]
@DiegoSanjuan, @jim-phillips, @JimGreene30, ☝️ ?

**Comment by jim-phillips** [comment]
I merged the redirect in CTL for the old kb name to the new one.  I should have waited for this.
@DiegoSanjuan please review by tomorrow so we can merge.

**Pull request merged**
