### PR TITLE
Add Kubernetes directory and getting started guide

### PR DESCRIPTION
**Pull request by ckleban**
Looking to add new kubernetes directory and getting started guide.
Also, removing old private cloud commit.

### CODE REVIEW

**Comment by nathanyoung** [comment]
@ckleban is your intention to add a "kubernetes" category to the KB landing page? https://www.ctl.io/knowledge-base/

Kubernetes is a Google brand, so I'm not sure how appropriate that would be for our website. Is there a more generic term that we can use as a category?

**Comment by ckleban** [comment]
Yes. That was my intent. Kubernetes is an open source project that google
started. Similar to openstack is an open source project that rackspace
started. I think it would be fine to create the kubernetes sub folder and
place this in there.

However, if that isn't desired, I'm not exactly sure where the best place
is. General could work. Eco-system could work (But I'm not in that team).
Another option is to create a group/category called "Container Services"
and place this in there.

**Comment by nathanyoung** [comment]
I think a more generic containers category would be the best option. It provides a place for other container-centric articles to live that aren't kubernetes specific. However we need to design a icon for the new category before this gets published. Can you update your pull request and change the "kuburnetes" category to `Container Services`?

**Comment by ckleban** [comment]
Okay. I will close this PR and submit a new one.

**Pull request closed without merging**
