### PR TITLE
Master

### PR DESCRIPTION
**Pull request by jmalmadclc**
Updated formatting of OVF/OVA best practices document.

### CODE REVIEW

**Comment by jmalmadclc** [comment]
Can someone assist with this merge? There is a travis error around an "&" character in the ovfova-import document, despite that character not appearing in the entire article. Thanks.

**Comment by osbornm** [comment]
1) Pull requests need a meaningful title not just "master"
2) links to other KB articles need to be relative. you have at least one that uses a full qualified domain that is wrong. e.g Centurylinkcloud.com. (https://github.com/CenturyLinkCloud/PublicKB/pull/389/files#diff-df18b9ce2644a845a391f644afedb4c2R22)
3)  remove the angle brackets around the noc email or use a value `[noc@ctl.io](mailto:noc@ctl.io)` link.

Because we want meaningful commit messages I'm closing this PR, please open a new one once you have addressed all three issues.

**Comment by jmalmadclc** [comment]
Matt- Made all changes as suggested, found in #398. Still getting a different error around:

File '/home/travis/build/CenturyLinkCloud/PublicKB/Service Taks/supported-guest-operating-systems-for-ovaovf-import.md' not found. Is there a file extension? Are the file extension and path correct? (Referenced from '/home/travis/build/CenturyLinkCloud/PublicKB/Service Tasks/best-practices-and-preparation-for-a-virtual-machineovfova-import.md')

despite the link being: "Validate the [Guest Operating System is supported on the CenturyLink Cloud for Import](../Service Taks/supported-guest-operating-systems-for-ovaovf-import.md)"

One last question, Nathan had said that he created a Disaster Recovery folder under the publick KB github but that it wouldn't be shown until articles had posted into it- I attempted to post one, it is still not displayed, not sure if that is because it is all bundled within this single request or not (as I was having github corruption issues for quite some time which prevented my from my normal submission cadence. At least we aren't getting that myseterious "&" error anymore. Thanks so much for you patience and insight- incredibly valuable.

**Comment by jmalmadclc** [comment]
Matt-


1.       Irrefutable and totally my fault.

2.       I don’t think that this exists in my local repo copy: see blow

a.       Validate the [Guest Operating System is supported on the CenturyLink Cloud for Import](../Service Taks/supported-guest-operating-systems-for-ovaovf-import.md) (this is what shows on my local copy)

3.       My local copy also shows the correct formatting for the NOC email: [noc@ctl.io](mailto:noc@ctl.io)
Thoughts?

Sorry to be a PITA. While I have you hear- Nathan said to me that he created a “disaster recovery folder within our git account, but that it would not appear until we had some articles residing within in it- I am attempting to put some safehaven troubleshooting docs in there and just wanted a sanity check if that is the appropriate way to prceed.

Thanks!

Jake

Jacob Malmad
Sr. Cloud Architect
CenturyLink Cloud 
Mobile: 203.844.0516
Email: jake.malmad@centurylink.com<mailto:jake.malmad@centurylinkcloud.com> 
www.centurylinkcloud.com<http://www.centurylinkcloud.com/>

**Comment by osbornm** [comment]
for 2 and 3 those changes were not pushed up to the server and only lived on your computer. Your new PR has them.

**Comment by jmalmadclc** [comment]
Matt-

I think we should be good to go now- I fixed the errors you pointed out. Thank you SO very much, this was driving me nuts and the misleading CI error had me running in circles.

Let me know if anything further needs to be fixed and I will get to it right away, just want these committed so I can move on to the other docs sitting here waiting; my apologies as it has been a hellish 3 months as I am not only fulfilling my standard duties but have been the defacto SafeHaven 3.1 QA team (all of which has been done in production after 3.1 was released in July).

Sorry if I caused any grief, and thanks for your patience.

Best,

Jake

Jacob Malmad
Sr. Cloud Architect
CenturyLink Cloud 
Mobile: 203.844.0516
Email: jake.malmad@centurylink.com<mailto:jake.malmad@centurylinkcloud.com> 
www.centurylinkcloud.com<http://www.centurylinkcloud.com/>

**Pull request closed without merging**
